<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
	    <groupId>com.alibaba.otter</groupId>
	    <artifactId>otter</artifactId>
	    <version>4.2.19-SNAPSHOT</version>
	</parent>
	<groupId>com.alibaba.otter</groupId>
	<artifactId>manager</artifactId>
	<packaging>pom</packaging>
	<name>manager module for otter</name>
	<version>4.2.19-SNAPSHOT</version>
	<url>http://github.com/alibaba/otter</url>

	<modules>
		<module>biz</module>
		<module>web</module>
		<module>deployer</module>
	</modules>

	<properties>
		<webx_version>3.2.0</webx_version>
	</properties>

	<dependencyManagement>
		<dependencies>
            <!-- WebX 3 -核心模块 -->
			<!-- spring -->
		</dependencies>
	</dependencyManagement>
</project>
