spring.application.name=otter-manager
spring.config.import=classpath:otter.properties
spring.main.allow-circular-references=true
spring.lifecycle.timeout-per-shutdown-phase=30s
server.shutdown=graceful
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
server.port=${otter.port:8080}
server.address=${otter.address:0.0.0.0}

spring.aop.proxy-target-class=false
