spring.application.name=otter-node
spring.config.import=classpath:otter.properties
spring.main.allow-circular-references=true
spring.lifecycle.timeout-per-shutdown-phase=30s
server.shutdown=graceful
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never

spring.aop.proxy-target-class=false
